import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  IsIn,
  IsInt,
  IsObject,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
  Max,
  Min,
} from 'class-validator';

export const OPEN_DID_CREDENTIAL_TYPES = [
  'entry',
  'adult',
  'student',
  'staff',
  'admin',
] as const;

export type OpenDidCredentialTypeValue =
  (typeof OPEN_DID_CREDENTIAL_TYPES)[number];

export const OPEN_DID_WALLET_FLOW_TYPES = ['issue', 'verify'] as const;

export const OPEN_DID_WALLET_FLOW_STATUSES = [
  'offer_created',
  'profile_requested',
  'request_submitted',
  'completed',
  'failed',
  'expired',
] as const;

export class ListOpenDidWalletTransactionsQueryDto {
  @ApiPropertyOptional({ enum: OPEN_DID_WALLET_FLOW_TYPES })
  @IsOptional()
  @IsIn(OPEN_DID_WALLET_FLOW_TYPES)
  flowType?: (typeof OPEN_DID_WALLET_FLOW_TYPES)[number];

  @ApiPropertyOptional({ enum: OPEN_DID_WALLET_FLOW_STATUSES })
  @IsOptional()
  @IsIn(OPEN_DID_WALLET_FLOW_STATUSES)
  status?: (typeof OPEN_DID_WALLET_FLOW_STATUSES)[number];

  @ApiPropertyOptional({ default: 20, minimum: 1, maximum: 100 })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  @Max(100)
  limit?: number;

  @ApiPropertyOptional({ default: 0, minimum: 0 })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(0)
  offset?: number;
}

export class CreateOpenDidIssueOfferDto {
  @ApiProperty({
    description:
      'CamPass credential id. The credential must belong to the authenticated user and have status=issued.',
  })
  @IsString()
  @IsUUID()
  credentialId: string;
}

export class CreateOpenDidVerifyOfferDto {
  @ApiProperty({ enum: OPEN_DID_CREDENTIAL_TYPES })
  @IsIn(OPEN_DID_CREDENTIAL_TYPES)
  credentialType: OpenDidCredentialTypeValue;

  @ApiPropertyOptional({
    description:
      'Optional request id sent to the official verifier. Defaults to a generated UUID.',
  })
  @IsOptional()
  @IsString()
  @MaxLength(100)
  requestId?: string;
}

export class RequestOpenDidIssueProfileDto {
  @ApiPropertyOptional({
    description:
      'CamPass OpenDID wallet transaction id returned by issue-offer. Recommended for frontend correlation.',
  })
  @IsOptional()
  @IsString()
  @IsUUID()
  walletTransactionId?: string;

  @ApiProperty()
  @IsString()
  txId: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(100)
  requestId?: string;

  @ApiPropertyOptional({
    description:
      'Holder wallet DID. Defaults to the authenticated CamPass user DID when omitted.',
  })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  holderDid?: string;

  @ApiPropertyOptional({
    description:
      'Official OpenDID holder PII field, passed through only when the wallet flow provides it.',
  })
  @IsOptional()
  @IsString()
  @MaxLength(500)
  holderPii?: string;
}

export class InspectOpenDidIssueProposeDto {
  @ApiPropertyOptional({
    description:
      'CamPass OpenDID wallet transaction id returned by issue-offer.',
  })
  @IsOptional()
  @IsString()
  @IsUUID()
  walletTransactionId?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(100)
  requestId?: string;

  @ApiPropertyOptional({
    description:
      'OpenDID txId. Defaults to the transaction txId when omitted.',
  })
  @IsOptional()
  @IsString()
  txId?: string;

  @ApiPropertyOptional({
    description:
      'OpenDID VC plan id. Defaults to the transaction vcPlanId when omitted.',
  })
  @IsOptional()
  @IsString()
  vcPlanId?: string;

  @ApiPropertyOptional({
    description:
      'OpenDID issuer DID or issuer identifier supplied by the holder flow.',
  })
  @IsOptional()
  @IsString()
  @MaxLength(300)
  issuer?: string;

  @ApiPropertyOptional({
    description:
      'OpenDID offer id. Defaults to the transaction offerId when omitted.',
  })
  @IsOptional()
  @IsString()
  offerId?: string;
}

export class RequestOpenDidIssueVcDto {
  @ApiPropertyOptional({
    description:
      'CamPass OpenDID wallet transaction id returned by issue-offer.',
  })
  @IsOptional()
  @IsString()
  @IsUUID()
  walletTransactionId?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(100)
  requestId?: string;

  @ApiProperty()
  @IsString()
  txId: string;

  @ApiPropertyOptional({
    description: 'OpenDID E2E agreement payload from the holder wallet.',
  })
  @IsOptional()
  @IsObject()
  accE2e?: Record<string, unknown>;

  @ApiProperty({
    description: 'Encrypted request VC payload generated by the holder wallet.',
  })
  @IsString()
  encReqVc: string;
}

export class CompleteOpenDidIssueVcDto {
  @ApiPropertyOptional({
    description:
      'CamPass OpenDID wallet transaction id returned by issue-offer.',
  })
  @IsOptional()
  @IsString()
  @IsUUID()
  walletTransactionId?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(100)
  requestId?: string;

  @ApiProperty()
  @IsString()
  txId: string;

  @ApiProperty({
    description: 'OpenDID VC id returned/stored by the holder wallet.',
  })
  @IsString()
  vcId: string;
}

export class RequestOpenDidVerifyProfileDto {
  @ApiPropertyOptional({
    description:
      'CamPass OpenDID wallet transaction id returned by verify-offer. Recommended for frontend correlation.',
  })
  @IsOptional()
  @IsString()
  @IsUUID()
  walletTransactionId?: string;

  @ApiProperty()
  @IsString()
  offerId: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  txId?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(100)
  requestId?: string;
}

export class RequestOpenDidVerifyVpDto {
  @ApiPropertyOptional({
    description:
      'CamPass OpenDID wallet transaction id returned by verify-offer.',
  })
  @IsOptional()
  @IsString()
  @IsUUID()
  walletTransactionId?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(100)
  requestId?: string;

  @ApiProperty()
  @IsString()
  txId: string;

  @ApiPropertyOptional({
    description: 'OpenDID E2E agreement payload from the holder wallet.',
  })
  @IsOptional()
  @IsObject()
  accE2e?: Record<string, unknown>;

  @ApiProperty({
    description: 'Encrypted VP payload generated by the holder wallet.',
  })
  @IsString()
  encVp: string;
}

export class ConfirmOpenDidVerifyDto {
  @ApiPropertyOptional({
    description:
      'CamPass OpenDID wallet transaction id returned by verify-offer.',
  })
  @IsOptional()
  @IsString()
  @IsUUID()
  walletTransactionId?: string;

  @ApiPropertyOptional({
    description:
      'OpenDID offer id. Defaults to the transaction offerId when omitted.',
  })
  @IsOptional()
  @IsString()
  offerId?: string;
}
