#!/usr/bin/env bash
set -euo pipefail

ISSUER_CONTAINER="${OPENDID_ISSUER_DB_CONTAINER:-campass-opendid-issuer-db}"
VERIFIER_CONTAINER="${OPENDID_VERIFIER_DB_CONTAINER:-campass-opendid-verifier-db}"
DB_USER="${OPENDID_DB_USERNAME:-omn}"
ISSUER_DB="${OPENDID_ISSUER_DB_NAME:-issuer}"
VERIFIER_DB="${OPENDID_VERIFIER_DB_NAME:-verifier}"
ISSUER_BASE_URL="${OPENDID_ISSUER_BASE_URL:-http://localhost:8091}"
VERIFIER_BASE_URL="${OPENDID_VERIFIER_BASE_URL:-http://localhost:8092}"

require_command() {
  local command_name="$1"
  if ! command -v "$command_name" >/dev/null 2>&1; then
    echo "$command_name is required." >&2
    exit 1
  fi
}

psql_json() {
  local container="$1"
  local database="$2"
  local sql="$3"

  docker exec "$container" \
    psql -U "$DB_USER" -d "$database" -t -A -v ON_ERROR_STOP=1 \
    -c "select coalesce(json_agg(row_to_json(t)), '[]'::json) from ($sql) t;"
}

require_command docker
require_command node

ISSUER_INFO="$(psql_json "$ISSUER_CONTAINER" "$ISSUER_DB" \
  "select id, did, name, status, server_url from issuer order by id")"
ISSUER_SCHEMAS="$(psql_json "$ISSUER_CONTAINER" "$ISSUER_DB" \
  "select id, vc_schema_id, title, version from vc_schema order by id")"
ISSUER_PROFILES="$(psql_json "$ISSUER_CONTAINER" "$ISSUER_DB" \
  "select ip.id, ip.vc_plan_id, ip.title, ip.definition_id, ip.zkp_enabled, vs.vc_schema_id, vs.title as vc_schema_title from issue_profile ip left join vc_schema vs on vs.id = ip.vc_schema_id order by ip.id")"
ISSUER_DEFINITIONS="$(psql_json "$ISSUER_CONTAINER" "$ISSUER_DB" \
  "select id, definition_id, schema_id, alias, tag, status from zkp_credential_definition order by id")"
VERIFIER_INFO="$(psql_json "$VERIFIER_CONTAINER" "$VERIFIER_DB" \
  "select id, did, name, status, server_url from verifier order by id")"
VERIFIER_POLICIES="$(psql_json "$VERIFIER_CONTAINER" "$VERIFIER_DB" \
  "select id, policy_id, policy_title, policy_type, policy_profile_id, payload_id from policy order by id")"

export ISSUER_INFO
export ISSUER_SCHEMAS
export ISSUER_PROFILES
export ISSUER_DEFINITIONS
export VERIFIER_INFO
export VERIFIER_POLICIES

node - "$ISSUER_BASE_URL" "$VERIFIER_BASE_URL" <<'NODE'
const [
  ,
  ,
  issuerBaseUrl,
  verifierBaseUrl,
] = process.argv;

const credentialTypes = ['entry', 'adult', 'student', 'staff', 'admin'];
const envPrefix = {
  entry: 'OPENDID_ENTRY',
  adult: 'OPENDID_ADULT',
  student: 'OPENDID_STUDENT',
  staff: 'OPENDID_STAFF',
  admin: 'OPENDID_ADMIN',
};
const fallbackSchemaId = {
  entry: 'campass-entry-v1',
  adult: 'campass-adult-v1',
  student: 'campass-student-v1',
  staff: 'campass-staff-v1',
  admin: 'campass-admin-v1',
};
const fallbackSchemaName = {
  entry: 'campass_entry',
  adult: 'campass_adult',
  student: 'campass_student',
  staff: 'campass_staff',
  admin: 'campass_admin',
};

function parseEnvJson(name) {
  try {
    return JSON.parse(process.env[name] ?? '[]');
  } catch (error) {
    throw new Error(`${name} was not valid JSON: ${error.message}`);
  }
}

const issuerInfo = parseEnvJson('ISSUER_INFO');
const issuerSchemas = parseEnvJson('ISSUER_SCHEMAS');
const issuerProfiles = parseEnvJson('ISSUER_PROFILES');
const issuerDefinitions = parseEnvJson('ISSUER_DEFINITIONS');
const verifierInfo = parseEnvJson('VERIFIER_INFO');
const verifierPolicies = parseEnvJson('VERIFIER_POLICIES');

function normalize(value) {
  return String(value ?? '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_');
}

function scoreCandidate(type, ...values) {
  const text = normalize(values.filter(Boolean).join(' '));
  const direct = [`campass_${type}`, `campass_${type}_v1`, type];
  return direct.reduce((score, token) => score + (text.includes(token) ? 1 : 0), 0);
}

function bestMatch(type, rows, fields) {
  return rows
    .map((row) => ({
      row,
      score: scoreCandidate(type, ...fields.map((field) => row[field])),
    }))
    .filter((item) => item.score > 0)
    .sort((a, b) => b.score - a.score)[0]?.row;
}

function q(value) {
  return `"${String(value ?? '').replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

function line(key, value, fallback = '') {
  if (value !== undefined && value !== null && String(value).trim() !== '') {
    console.log(`${key}=${q(value)}`);
    return;
  }

  if (fallback) {
    console.log(`${key}=${q(fallback)}`);
    console.log(`# TODO ${key}: confirm generated OpenDID value in Admin Console.`);
    return;
  }

  console.log(`${key}=""`);
  console.log(`# TODO ${key}: fill after OpenDID Admin Console setup.`);
}

const activeIssuer = issuerInfo.find((row) => row.did) ?? issuerInfo[0];
const activeVerifier = verifierInfo.find((row) => row.did) ?? verifierInfo[0];

console.log('# Generated by npm run opendid:export-env');
console.log('# Review TODO lines before enabling OpenDID issuance/verification.');
console.log('');
line('OPENDID_MODE', 'self_hosted');
line('OPENDID_CREDENTIAL_ISSUANCE_ENABLED', 'false');
line('OPENDID_VERIFICATION_ENABLED', 'false');
line('OPENDID_CREDENTIAL_ISSUE_MODE', 'official_wallet');
line('OPENDID_CREDENTIAL_VERIFY_MODE', 'official_vp');
line('OPENDID_ISSUER_BASE_URL', issuerBaseUrl);
line('OPENDID_VERIFIER_BASE_URL', verifierBaseUrl);
line('OPENDID_ISSUER_DID', activeIssuer?.did);
line('OPENDID_ISSUER_KID', '');
line('OPENDID_ISSUER_SERVICE_ID', 'campass');
line('OPENDID_CREDENTIAL_ISSUE_PATH', '/issuer/api/v1/issue-vc');
line('OPENDID_CREDENTIAL_REVOKE_PATH', '/issuer/api/v1/revoke-vc');
line('OPENDID_CREDENTIAL_VERIFY_PATH', '/verifier/api/v1/request-verify');
line('OPENDID_ISSUE_OFFER_PATH', '/issuer/api/v1/request-offer');
line('OPENDID_ISSUE_INSPECT_PROPOSE_PATH', '/issuer/api/v1/inspect-propose-issue');
line('OPENDID_ISSUE_PROFILE_PATH', '/issuer/api/v1/generate-issue-profile');
line('OPENDID_ISSUE_COMPLETE_PATH', '/issuer/api/v1/complete-vc');
line('OPENDID_ISSUE_RESULT_PATH', '/issuer/api/v1/issue-vc/result');
line('OPENDID_VERIFY_OFFER_PATH', '/verifier/api/v1/request-offer-qr');
line('OPENDID_VERIFY_PROFILE_PATH', '/verifier/api/v1/request-profile');
line('OPENDID_VERIFY_CONFIRM_PATH', '/verifier/api/v1/confirm-verify');
line('OPENDID_ISSUER_HEALTH_PATH', '/actuator/health');
line('OPENDID_VERIFIER_HEALTH_PATH', '/actuator/health');
console.log('');

for (const type of credentialTypes) {
  const schema = bestMatch(type, issuerSchemas, ['vc_schema_id', 'title']);
  const profile = bestMatch(type, issuerProfiles, [
    'vc_plan_id',
    'title',
    'vc_schema_id',
    'vc_schema_title',
    'definition_id',
  ]);
  const definition = bestMatch(type, issuerDefinitions, [
    'definition_id',
    'schema_id',
    'alias',
    'tag',
  ]);
  const policy = bestMatch(type, verifierPolicies, [
    'policy_id',
    'policy_title',
    'policy_type',
    'policy_profile_id',
  ]);
  const prefix = envPrefix[type];

  console.log(`# ${type.toUpperCase()} VC`);
  line(`${prefix}_SCHEMA_ID`, schema?.vc_schema_id ?? profile?.vc_schema_id, fallbackSchemaId[type]);
  line(`${prefix}_SCHEMA_NAME`, fallbackSchemaName[type]);
  line(`${prefix}_VC_PLAN_ID`, profile?.vc_plan_id);
  line(`${prefix}_ISSUE_PROFILE_ID`, profile?.id);
  line(`${prefix}_CREDENTIAL_DEFINITION_ID`, profile?.definition_id ?? definition?.definition_id);
  line(`${prefix}_VERIFY_POLICY_ID`, policy?.policy_id);
  console.log('');
}

if (!activeIssuer?.did) {
  console.log('# WARNING: issuer DID is not registered yet.');
}

if (!activeVerifier?.did) {
  console.log('# WARNING: verifier DID is not registered yet.');
}

if (!issuerSchemas.length) {
  console.log('# WARNING: no issuer VC schemas found.');
}

if (!issuerProfiles.length) {
  console.log('# WARNING: no issuer issue profiles / VC plans found.');
}

if (!verifierPolicies.length) {
  console.log('# WARNING: no verifier policies found.');
}
NODE
