#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
WORKDIR="${OPENDID_WORKDIR:-$BACKEND_DIR/.opendid}"
COMPOSE_DIR="${OPENDID_COMPOSE_DIR:-$WORKDIR/compose}"

ISSUER_REPO="$WORKDIR/did-issuer-server"
VERIFIER_REPO="$WORKDIR/did-verifier-server"
ISSUER_SOURCE="$ISSUER_REPO/source"
VERIFIER_SOURCE="$VERIFIER_REPO/source"
ISSUER_CONFIG_SOURCE="$ISSUER_SOURCE/did-issuer-server/src/main/resources/config"
ISSUER_PROPERTIES_SOURCE="$ISSUER_SOURCE/did-issuer-server/src/main/resources/properties"
VERIFIER_CONFIG_SOURCE="$VERIFIER_SOURCE/did-verifier-server/src/main/resources/config"
VERIFIER_PROPERTIES_SOURCE="$VERIFIER_SOURCE/did-verifier-server/src/main/resources/properties"

require_dir() {
  local path="$1"
  local message="$2"
  if [ ! -d "$path" ]; then
    echo "$message" >&2
    echo "Run: npm run opendid:clone" >&2
    exit 1
  fi
}

copy_dir_contents() {
  local source_dir="$1"
  local target_dir="$2"
  mkdir -p "$target_dir"
  if [ -d "$source_dir" ]; then
    cp -R "$source_dir"/. "$target_dir"/
  fi
}

require_dir "$ISSUER_CONFIG_SOURCE" "Issuer config source was not found."
require_dir "$VERIFIER_CONFIG_SOURCE" "Verifier config source was not found."

mkdir -p "$COMPOSE_DIR/issuer-config"
mkdir -p "$COMPOSE_DIR/verifier-config"

cp "$BACKEND_DIR/opendid/docker-compose.self-hosted.example.yml" \
  "$COMPOSE_DIR/docker-compose.yml"

copy_dir_contents "$ISSUER_CONFIG_SOURCE" "$COMPOSE_DIR/issuer-config"
copy_dir_contents "$ISSUER_PROPERTIES_SOURCE" "$COMPOSE_DIR/issuer-config"
copy_dir_contents "$VERIFIER_CONFIG_SOURCE" "$COMPOSE_DIR/verifier-config"
copy_dir_contents "$VERIFIER_PROPERTIES_SOURCE" "$COMPOSE_DIR/verifier-config"

cat > "$COMPOSE_DIR/README.md" <<EOF
# Local OpenDID Compose Workspace

Generated by:

\`\`\`bash
npm run opendid:prepare
\`\`\`

This folder is ignored by git. Edit copied config files here, not the files under
the official cloned repositories. The compose helper syncs these config folders
into Docker named volumes before starting the official servers.

## Build Images

\`\`\`bash
cd "$ISSUER_SOURCE"
docker build -t did-issuer-server -f Dockerfile .

cd "$VERIFIER_SOURCE"
docker build -t did-verifier-server -f Dockerfile .
\`\`\`

## Edit These Files

Issuer:

- issuer-config/application.yml
- issuer-config/application-database.yml
- issuer-config/application-wallet.yml
- issuer-config/application-blockchain.yml
- issuer-config/blockchain.properties

Verifier:

- verifier-config/application.yml
- verifier-config/application-database.yml or application-databases-sample.yml
- verifier-config/application-blockchain.yml
- verifier-config/blockchain.properties

## Run

\`\`\`bash
cd "$COMPOSE_DIR"
npm run opendid:up
\`\`\`

Config volume sync:

- issuer-config -> campass_opendid_issuer_config
- verifier-config -> campass_opendid_verifier_config

## CamPass Backend Env

\`\`\`env
OPENDID_ISSUER_BASE_URL="http://localhost:8091"
OPENDID_VERIFIER_BASE_URL="http://localhost:8092"
\`\`\`
EOF

cat <<EOF

OpenDID compose workspace is ready:
  $COMPOSE_DIR

Copied issuer config:
  $COMPOSE_DIR/issuer-config

Copied verifier config:
  $COMPOSE_DIR/verifier-config

Next:
  1. Edit copied config files under $COMPOSE_DIR/*-config
  2. Build official Docker images:
     cd "$ISSUER_SOURCE" && docker build -t did-issuer-server -f Dockerfile .
     cd "$VERIFIER_SOURCE" && docker build -t did-verifier-server -f Dockerfile .
  3. Run:
     cd "$COMPOSE_DIR" && docker compose up -d
EOF
